// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/components/defaultLayout.vue')['default']
    EmptyLayout: typeof import('./src/components/emptyLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VContent: typeof import('vuetify/components')['VContent']
    VIcon: typeof import('vuetify/components')['VIcon']
    VLayout: typeof import('vuetify/components')['VLayout']
    VMain: typeof import('vuetify/components')['VMain']
    VRow: typeof import('vuetify/components')['VRow']
    VTextField: typeof import('vuetify/components')['VTextField']
  }
}

export {}
